## Numpy Tutorial

#### Hands on!

In [2]:
import sys
import numpy as np

#### Basic Numpy Arrays

In [29]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([0, -5, 1.5, 2])

In [30]:
a[0], a[1]
a[0:]

array([1, 2, 3, 4, 5])

In [31]:
a[1:3]


array([2, 3])

In [32]:
a[1:-1]

array([2, 3, 4])

In [33]:
a[::2]

array([1, 3, 5])

In [34]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.5), np.float64(2.0))

In [35]:
b[[0, 2, -1]]

array([0. , 1.5, 2. ])

#### Array Types

In [36]:
a

array([1, 2, 3, 4, 5])

In [37]:
b

array([ 0. , -5. ,  1.5,  2. ])

In [39]:
b.dtype

dtype('float64')

In [3]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

#### Demensions and Shapes

In [5]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A.shape

(2, 3)

In [8]:
A.ndim

2

In [9]:
A.size

6

In [10]:
B = np.array([
    [
        [12, 11, 19],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
B

array([[[12, 11, 19],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [11]:
B.shape

(2, 2, 3)

In [12]:
B.ndim

3

In [13]:
B.size

12

In [19]:
C = np.array([
    [12, 11, 19],
    [9, 8, 7],
    [13, 14, 15]
])

In [20]:
C.shape

(3, 3)

In [21]:
C[0][2]

np.int64(19)

In [22]:
C[0:2]

array([[12, 11, 19],
       [ 9,  8,  7]])

In [24]:
C[:, :2]

array([[12, 11],
       [ 9,  8],
       [13, 14]])

In [25]:
C[:2, :2]

array([[12, 11],
       [ 9,  8]])

In [27]:
C[1][2] = 98
C

array([[12, 11, 19],
       [ 9,  8, 98],
       [13, 14, 15]])

#### Summary Statistics

In [28]:
a = np.array([1, 2, 3, 4])

In [29]:
a.sum()

np.int64(10)

In [30]:
a.std()

np.float64(1.118033988749895)

In [31]:
a.mean()

np.float64(2.5)

In [32]:
a.var()

np.float64(1.25)

In [34]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [35]:
A.sum()

np.int64(45)

In [36]:
A.mean()

np.float64(5.0)

In [37]:
A.sum(axis=0)

array([12, 15, 18])

In [38]:
A.sum(axis=1)

array([ 6, 15, 24])

In [39]:
A.std()

np.float64(2.581988897471611)

In [40]:
A.mean(axis=0)

array([4., 5., 6.])

In [41]:
A.mean(axis=1)

array([2., 5., 8.])

In [42]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [43]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

#### Broadcasting and Vectorized operations

In [3]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [4]:
a + 20

array([20, 21, 22, 23])

In [6]:
a += 100

In [7]:
a

array([100, 101, 102, 103])

In [8]:
l = [0, 1, 2, 3]

In [9]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [12]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [13]:
b = np.array([10, 10, 10, 10])


In [14]:
a + b

array([10, 11, 12, 13])

In [16]:
a * b

array([ 0, 10, 20, 30])

In [ ]:
c = np.dot(a, b)

60

In [25]:
a = np.array([11, -2, 3])
b = np.array([1, 2, -3])
c = np.cross(a, b)
c

array([ 0, 36, 24])

In [28]:
a = np.arange(4)

In [29]:
a >= 2

array([False, False,  True,  True])

In [30]:
a[a>=2]

array([2, 3])

In [32]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [36]:
A = np.random.randint(100, size=[3, 3])
A

array([[85, 92, 59],
       [38, 12, 59],
       [92, 38, 87]], dtype=int32)

In [39]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([85, 59, 12, 92, 87], dtype=int32)

#### Linear Algebra

In [40]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [41]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [42]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [43]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [44]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [45]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

#### User numpy functions

##### Random

In [3]:
np.random.random(size=2)

array([0.24973731, 0.58907955])

In [4]:
np.random.normal(size=2)

array([-0.23758829,  0.41064134])

In [5]:
np.random.rand(2, 4)

array([[0.48630886, 0.85880818, 0.61692934, 0.6995152 ],
       [0.2846364 , 0.12479578, 0.36879306, 0.25821611]])

##### Arange

In [6]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [9]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

##### Reshape

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

##### Zero, One, Empty

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros([3, 3], dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.empty([2, 2])

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

##### Identity and Eye

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(8, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])