In [36]:
import numpy as np
import sys
print(np.__version__)

2.3.4


In [4]:
np.zeros(10, dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [5]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
np.ones([2, 2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

In [10]:
np.ones([3, 2], dtype=np.float16)

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float16)

In [12]:
x = np.arange(4, dtype=np.int8)
np.ones_like(x)

array([1, 1, 1, 1], dtype=int8)

In [19]:
x = np.array([
        [3, 3, 2],
        [1, 2, 3]
    ], 
    dtype=np.int8)
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [22]:
np.ones([4, 4], dtype=np.int8) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

In [26]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=np.int8)

np.ones_like(x) * 7

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int8)

In [29]:
np.identity(3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [32]:
np.random.randint(10, size=3)

array([4, 0, 9], dtype=int32)

In [33]:
np.random.randn(3, 3, 3)

array([[[ 1.26480321,  0.50137075, -0.88439715],
        [ 0.77803477,  0.21667651, -0.91825747],
        [ 0.32460904, -0.8375149 ,  0.74226518]],

       [[ 0.03979951,  1.7830082 ,  0.03991355],
        [-0.42415994,  0.87605653,  1.35283981],
        [ 1.32051115, -0.11914157, -1.29330473]],

       [[ 1.05924935,  0.13153155, -0.0352433 ],
        [-0.04147301, -1.18707509,  0.38185478],
        [ 0.38788585, -0.81548429,  0.42040932]]])

In [39]:
x = [1, 2, 3, 4, 5, 6]
y = np.array(x)

In [43]:
x = np.array([5, 2, 3], dtype=np.int8)
print(x, id(x))
y = np.copy(x)
print(y, id(y))

[5 2 3] 2100915415216
[5 2 3] 2100914794352


In [47]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [48]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [49]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
z = np.array([
    [1, 2],
    [3, 4]
])
z.size * z.itemsize

32

In [61]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1] = np.ones(4, dtype=np.int8)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [63]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

In [64]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

np.False_

In [65]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

np.True_